In [4]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
movies_data = pd.read_csv('movies.csv')

In [6]:
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [7]:
movies_data.shape

(4803, 24)

In [8]:
selected_features = ['genres', 'keywords', 'cast', 'director', 'tagline', 'overview']
print(selected_features)

['genres', 'keywords', 'cast', 'director', 'tagline', 'overview']


In [9]:
for feature in selected_features:
    movies_data[feature] = movies_data[feature].fillna('')

In [10]:
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['cast']+' '+movies_data['director']+' '+movies_data['tagline']+' '+movies_data['overview']
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  Edward Burns Kerry Bish\u00e9 ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      Daniel Henney Eliza Coupe Bill Paxton Alan R...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [11]:
vectorizer = TfidfVectorizer()

In [12]:
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 307355 stored elements and shape (4803, 30592)>
  Coords	Values
  (0, 561)	0.05971816344971169
  (0, 703)	0.06846420517510078
  (0, 9754)	0.08513696797398294
  (0, 23977)	0.07941905576010944
  (0, 10023)	0.07960231361105431
  (0, 6601)	0.1498786462809525
  (0, 5279)	0.1549075340655008
  (0, 10796)	0.11095111375730655
  (0, 25413)	0.24369151759694266
  (0, 29469)	0.08637114089261566
  (0, 5592)	0.17322386697661618
  (0, 25232)	0.1336739112380023
  (0, 23619)	0.11047375838269538
  (0, 30145)	0.18243919685121024
  (0, 30543)	0.15064979633862852
  (0, 23578)	0.16802034155542864
  (0, 24802)	0.158925784923944
  (0, 29614)	0.15064979633862852
  (0, 25868)	0.11590870590502833
  (0, 15569)	0.171366691592621
  (0, 17784)	0.12285843797047787
  (0, 23134)	0.1498786462809525
  (0, 14180)	0.08418056281586364
  (0, 4288)	0.13213124585063996
  (0, 9065)	0.14505772980982928
  :	:
  (4802, 9588)	0.10415492266309316
  (4802, 21386)	0.08975511

In [13]:
similarity = cosine_similarity(feature_vectors)

In [14]:
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [15]:
print(similarity.shape)

(4803, 4803)


In [16]:
movie_name = input('Enter your favourite movie: ')

In [17]:
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [18]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

["Pirates of the Caribbean: At World's End", "Pirates of the Caribbean: Dead Man's Chest", 'Pirates of the Caribbean: On Stranger Tides']


In [19]:
close_match = find_close_match[0]
print(close_match)

Pirates of the Caribbean: At World's End


In [20]:
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

1


In [21]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, np.float64(0.050831680232069756)), (1, np.float64(1.0)), (2, np.float64(0.04356836213206876)), (3, np.float64(0.03583792901621507)), (4, np.float64(0.081384877974474)), (5, np.float64(0.05480226451884788)), (6, np.float64(0.03464284223828471)), (7, np.float64(0.08959075672089678)), (8, np.float64(0.06414933801459335)), (9, np.float64(0.05072415018688944)), (10, np.float64(0.06122134275795599)), (11, np.float64(0.04238109292507937)), (12, np.float64(0.3851406888044465)), (13, np.float64(0.11254120531783904)), (14, np.float64(0.09408058140240465)), (15, np.float64(0.06686921360253029)), (16, np.float64(0.0622484973643675)), (17, np.float64(0.11029140153896837)), (18, np.float64(0.10009055833228646)), (19, np.float64(0.08405749626475882)), (20, np.float64(0.0901448245141993)), (21, np.float64(0.039482880879324916)), (22, np.float64(0.05181665778162038)), (23, np.float64(0.04831071589440362)), (24, np.float64(0.054685118551715935)), (25, np.float64(0.05369071848626111)), (26, np.float

In [22]:
len(similarity_score)

4803

In [23]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(1, np.float64(1.0)), (12, np.float64(0.3851406888044465)), (199, np.float64(0.3075123972329583)), (536, np.float64(0.1886396429575348)), (129, np.float64(0.14051209824986935)), (384, np.float64(0.13418654881745073)), (1652, np.float64(0.13344409439278246)), (329, np.float64(0.1331062868318985)), (47, np.float64(0.12906558889989939)), (848, np.float64(0.1217075018840179)), (886, np.float64(0.11887229654532527)), (517, np.float64(0.11822843064472767)), (1635, np.float64(0.11654665385683566)), (549, np.float64(0.11510466857423199)), (1183, np.float64(0.11394934824750225)), (3033, np.float64(0.11361538044754717)), (4608, np.float64(0.11303786341079688)), (13, np.float64(0.11254120531783904)), (178, np.float64(0.1125044517128147)), (2040, np.float64(0.11221547227113861)), (128, np.float64(0.11153154511249223)), (17, np.float64(0.11029140153896837)), (85, np.float64(0.10952152469711178)), (2474, np.float64(0.1088070247288608)), (1095, np.float64(0.10799905764526214)), (3373, np.float64(0.1

In [24]:
print('Movies suggested for you: \n')

i=1
for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = movies_data[movies_data.index==index]['title'].values[0]
    if(i<30):
      print(i, '.', title_from_index)
      i+=1


Movies suggested for you: 

1 . Pirates of the Caribbean: At World's End
2 . Pirates of the Caribbean: Dead Man's Chest
3 . Pirates of the Caribbean: The Curse of the Black Pearl
4 . Anna and the King
5 . Thor
6 . Cast Away
7 . Dragonball Evolution
8 . The Lord of the Rings: The Return of the King
9 . Star Trek Into Darkness
10 . The Pirates! In an Adventure with Scientists!
11 . Mamma Mia!
12 . Exorcist: The Beginning
13 . The Replacement Killers
14 . Sphere
15 . The Mexican
16 . The Corruptor
17 . The Prophecy
18 . The Lone Ranger
19 . Rango
20 . The Glass House
21 . Angels & Demons
22 . Pirates of the Caribbean: On Stranger Tides
23 . Captain America: The Winter Soldier
24 . Arn: The Knight Templar
25 . Curse of the Golden Flower
26 . The Other Side of Heaven
27 . Cinderella
28 . The Lord of the Rings: The Fellowship of the Ring
29 . The Three Musketeers


In [28]:
import pickle

#

# Save the necessary components into a pickle file
pickle.dump(similarity, open('movie_recommendation_system.pkl', 'wb'))

In [26]:
import pickle
pickle.dump(movies_data, open('movies.pkl', 'wb'))


# Movie Recommendation System

In [27]:
movie_name = input('Enter your favourite movie: ')

list_of_all_titles = movies_data['title'].tolist()

close_match = find_close_match[0]

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you: \n')

i=1
for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = movies_data[movies_data.index==index]['title'].values[0]
    if(i<30):
      print(i, '.', title_from_index)
      i+=1

Movies suggested for you: 

1 . Pirates of the Caribbean: At World's End
2 . Pirates of the Caribbean: Dead Man's Chest
3 . Pirates of the Caribbean: The Curse of the Black Pearl
4 . Anna and the King
5 . Thor
6 . Cast Away
7 . Dragonball Evolution
8 . The Lord of the Rings: The Return of the King
9 . Star Trek Into Darkness
10 . The Pirates! In an Adventure with Scientists!
11 . Mamma Mia!
12 . Exorcist: The Beginning
13 . The Replacement Killers
14 . Sphere
15 . The Mexican
16 . The Corruptor
17 . The Prophecy
18 . The Lone Ranger
19 . Rango
20 . The Glass House
21 . Angels & Demons
22 . Pirates of the Caribbean: On Stranger Tides
23 . Captain America: The Winter Soldier
24 . Arn: The Knight Templar
25 . Curse of the Golden Flower
26 . The Other Side of Heaven
27 . Cinderella
28 . The Lord of the Rings: The Fellowship of the Ring
29 . The Three Musketeers
